### ISSUE TITLE
Define Resource Schema

### ISSUE THREAD

**Issue by wilfredeveloper** [permoK/jadi-DBMS#2]
Define the schema for the resources table, which will store information about various resources uploaded to the platform.

- [ ] Create resources table.
- [ ] Define fields for resources table (`downloadUrl`, `uploadedBy`, `title`, `description`, `size`, `cmsId`, `category`, `resourceTypeId`, `createdAt`, `updatedAt`).
- [ ] Add relations for resources table.

### ResourceType
| Field              | Type |
|--------------------|------|
| id                 | PK   |
| resource_type_name |      |

### Resource
| Field            | Type |
|------------------|------|
| id               | PK   |
| download_url     |      |
| uploaded_by      | FK   |
| title            |      |
| description      |      |
| size             |      |
| cms_id           |      |
| category         |      |
| resource_type_id | FK   |
| created_at       |      |
| updated_at       |      |

### ResourceTag
| Field        | Type |
|--------------|------|
| resource_id  | FK   |
| interest_id  | FK   |

## Relationships

- **ResourceType** `id` <--> `resource_type_id` in **Resource**
- **Interest** `id` <--> `interest_id` in **ResourceTag**
- **Resource** `id` <--> `resource_id` in **ResourceTag**

**Comment by permoK** [comment]
okay on it

**Comment by permoK** [comment]
fixed
